Extension { #name : #MatchToolPresenter }

{ #category : #'*RewriteTool-Tests' }
MatchToolPresenter >> astCode [

	"This accessor should ONLY be called in the tests. This is for not break encapsulation."

	^ astCode
]

{ #category : #'*RewriteTool-Tests' }
MatchToolPresenter >> astPattern [

	"This accessor should ONLY be called in the tests. This is for not break encapsulation."

	^ astPattern
]

{ #category : #'*RewriteTool-Tests' }
MatchToolPresenter >> bindingsTable [

	"This accessor should ONLY be called in the tests. This is for not break encapsulation."

	^ bindingsTable
]

{ #category : #'*RewriteTool-Tests' }
MatchToolPresenter >> codeEditor [

	"This accessor should ONLY be called in the tests. This is for not break encapsulation."

	^ codeEditor
]

{ #category : #'*RewriteTool-Tests' }
MatchToolPresenter >> matchesList [

	"This accessor should ONLY be called in the tests. This is for not break encapsulation."

	^ matchesList
]

{ #category : #'*RewriteTool-Tests' }
MatchToolPresenter >> methodCheckbox [

	"This accessor should ONLY be called in the tests. This is for not break encapsulation."

	^ methodCheckbox
]

{ #category : #'*RewriteTool-Tests' }
MatchToolPresenter >> ruleEditor [

	"This accessor should ONLY be called in the tests. This is for not break encapsulation."

	^ ruleEditor
]
