Extension { #name : #MethodsSelectorPresenter }

{ #category : #'*RewriteTool-Tests' }
MethodsSelectorPresenter >> classesFilteringListPresenter [

	^ classesListWithFilter
]

{ #category : #'*RewriteTool-Tests' }
MethodsSelectorPresenter >> methodsFilteringListPresenter [

	^ methodsListWithFilter
]

{ #category : #'*RewriteTool-Tests' }
MethodsSelectorPresenter >> packagesFilteringListPresenter [

	^ packagesListWithFilter
]
