Extension { #name : #RTChangesBrowser }

{ #category : #'*RewriteRuleTools-Tests' }
RTChangesBrowser >> buttonCancel [

	^ buttonCancel
]

{ #category : #'*RewriteRuleTools-Tests' }
RTChangesBrowser >> buttonOk [

	^ buttonOk
]

{ #category : #'*RewriteRuleTools-Tests' }
RTChangesBrowser >> changesTree [

	^ changesTree
]

{ #category : #'*RewriteRuleTools-Tests' }
RTChangesBrowser >> diffView [

	^ diffView
]
