Extension { #name : #ScopeSelectorPresenter }

{ #category : #'*RewriteRuleTools-Tests' }
ScopeSelectorPresenter >> classesFilteringListPresenter [

	^ classesListWithFilterPresenter
]

{ #category : #'*RewriteRuleTools-Tests' }
ScopeSelectorPresenter >> methodsFilteringListPresenter [

	^ methodsListWithFilterPresenter
]

{ #category : #'*RewriteRuleTools-Tests' }
ScopeSelectorPresenter >> packagesFilteringListPresenter [

	^ packagesListWithFilterPresenter
]
